### ISSUE TITLE
Is PAM_CLOSE_SESSION missing?

### ISSUE THREAD

**Issue by TimB87** [ifreund/dumb_runtime_dir#3]
Hi @ifreund,

we plan to use dumb_runtime_dir for CRUX upcoming release. Ideally I would want to place it in our `common-session` file, but it appears that `PAM_CLOSE_SESSION(3)` instructions are missing. I get an error with every service that uses pam when it tries to deconstruct a session:

```
❯ sudo echo foo
foo
doas: pam_close_session: Module is unknown
``` 

Is this something that can be added to this project?

**Comment by ifreund** [comment]
This seems to be a issue with your PAM configuration, make sure you've spelled `pam_dumb_runtime_dir.so` properly and your `pam.d` config files have the correct syntax. Also ensure that `pam_dumb_runtime_dir.so` is in the correct directory alongside your other PAM modules.

**Comment by TimB87** [comment]
I double checked spelling and `pam_dumb_runtime_dir.so` is correctly placed in `/lib/security`, as this is where CRUX stores them.
I haven't had the same problem with rundird.

These are the steps taken to generate a package:
```
make -C $name-$version PREFIX=""
make -C $name-$version DESTDIR=$PKG PREFIX="" install
```
Do you see anything wrong that maybe?

Edit:

I revised it to this with no help:
```
make -C $name-$version
make -C $name-$version DESTDIR=$PKG PAMDIR="/lib/security" install
```

This is my `/etc/pam.d/common-session`:
```
session       required    pam_unix.so

# optionally added
session       optional    pam_dumb_runtime_dir.so
session       optional    pam_loginuid.so
session       optional    pam_gnupg.so
session       optional    pam_gnome_keyring.so      auto_start
```

**Comment by ifreund** [comment]
Hmm, seems that PAM requires modules to define all functions even if they are a noop:
https://github.com/linux-pam/linux-pam/blob/b872b6e68a60ae351ca4c7eea6dfe95cd8f8d130/libpam/pam_dispatch.c#L102-L105

**Comment by ifreund** [comment]
Should be fixed by 11d0c5215107b9823f88afd364d29eae77582eef. Let me know if that solves your issue and I'll tag a release.

**Comment by TimB87** [comment]
This works perfectly fine over here, thank you!

**Comment by ifreund** [comment]
Thanks for testing, just tagged 1.0.4: https://github.com/ifreund/dumb_runtime_dir/releases/tag/v1.0.4
