### ISSUE TITLE
Create RUNTIME_DIR_PARENT ourselves if it doesn't exists?

### ISSUE THREAD

**Issue by stacyharper** [ifreund/dumb_runtime_dir#5]
The README explains:

> The user is responsible for ensuring that the RUNTIME_DIR_PARENT directory (/run/user by default) exists and is only writable by root.

The problem is that this move this responsibility to the distro, and there is no convenient way to do so. I'm from Alpine Linux, and I am trying to make this project to works OOTB, without requiring any action from the user, except installing this package.

Are you open to the idea that dumb_runtime_dir could create this directory itself?

**Comment by ifreund** [comment]
I don't have any intention of changing this.

For void linux for example it is done here: https://github.com/void-linux/void-runit/blob/329b891426efc093ad8c65e96364427c2fb25b54/core-services/00-pseudofs.sh#L8
